apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-02-10T17:45:00Z"
  labels:
    app: monica
  name: monica
  namespace: monicahq
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: monica
